image: debian/stable
packages:
  - mairix
  - emacs
sources:
  - https://git.sr.ht/~ane/counsel-mairix
secrets:
  - 1d566b53-84ba-4840-afac-e20f0b3b02ef
tasks:
  - unit-test: |
      cd counsel-mairix
      emacs -Q --batch -L . \
          --eval '(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")' \
          --eval '(package-initialize)' \
          --eval '(package-refresh-contents)' \
          --eval '(defun install-latest (p) 
                    (package-install 
                      (cadr (assoc p 
                             package-archive-contents 
                             (quote equal)))))' \
                             --eval '(install-latest (quote counsel))' \
          -l counsel-mairix.el \
          -l counsel-mairix-tests.el \
          --eval '(ert-run-tests-batch-and-exit (quote t))' 
  - mirror-to-github: |
      cd ~/counsel-mairix
      echo -e "Host github.com\n  IdentityFile /home/build/.ssh/1d566b53-84ba-4840-afac-e20f0b3b02ef\n  IdentitiesOnly yes\n  BatchMode yes" >> ~/.ssh/config
      ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      git remote add github git@github.com:ane/counsel-mairix.git
      git push --prune github +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
      
      
